# List of valid React app routes - these MUST be served by the SPA
# These MUST come before any council or parking routes to ensure proper rendering
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# We now serve these pages directly as static files, so we don't need these redirects
# [[redirects]]
#   from = "/local-authorities"
#   to = "/index.html"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/councils"
#   to = "/index.html"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/council-appeal-hub"
#   to = "/index.html"
#   status = 200
#   force = true

# [[redirects]]
#   from = "/council-list"
#   to = "/index.html"
#   status = 200
#   force = true

[[redirects]]
  from = "/appeal-help"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/faq"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200
  force = true

# STRICT PATTERNS for parking company pages - only match known formats  
# The Netlify function will provide additional validation to ensure only legitimate companies are processed
[[redirects]]
  from = "/apcoa-parking"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/euro-car-parks"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/parkingeye"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/smart-parking"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/rcp-parking"
  to = "/.netlify/functions/parking-seo"
  status = 200

# Individual company paths
[[redirects]]
  from = "/ukpc"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/nsl"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/nsgl"
  to = "/.netlify/functions/parking-seo"
  status = 200
  
[[redirects]]
  from = "/ocs"
  to = "/.netlify/functions/parking-seo"
  status = 200
  
[[redirects]]
  from = "/pess"
  to = "/.netlify/functions/parking-seo"
  status = 200

# Known council patterns - STRICT matching only with regex conditions
# This ensures only valid council patterns are processed by the function
[[redirects]]
  from = "/*-council"
  to = "/.netlify/functions/council-seo"
  status = 200
  conditions = {Pattern = ["/[a-z]+-council$"]}

[[redirects]]
  from = "/*-city-council"
  to = "/.netlify/functions/council-seo"
  status = 200
  conditions = {Pattern = ["/[a-z]+-city-council$"]}

[[redirects]]
  from = "/city-of-*"
  to = "/.netlify/functions/council-seo"
  status = 200
  conditions = {Pattern = ["/city-of-[a-z]+$"]}

# Explicitly listed single-word councils ONLY
[[redirects]]
  from = "/barnsley"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/birmingham"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/bradford"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/coventry"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/leicester"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/leeds"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/liverpool"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/manchester"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/nottingham"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/plymouth"
  to = "/.netlify/functions/council-seo"
  status = 200

# Common static files that should be served directly
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

# Serve our static HTML pages for the hub pages
[[redirects]]
  from = "/local-authorities"
  to = "/local-authorities.html"
  status = 200

[[redirects]]
  from = "/councils"
  to = "/councils.html"
  status = 200

[[redirects]]
  from = "/council-appeal-hub"
  to = "/council-appeal-hub.html"
  status = 200

# Handle all unknown paths with 404 - MUST BE LAST
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Ensure sitemap.xml and robots.txt are properly served
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# Enable Netlify Functions
[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"
