# List of valid React app routes - these MUST be served by the SPA
# These MUST come before any council or parking routes to ensure proper rendering
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/local-authorities"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/councils"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/council-appeal-hub"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/council-list"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/appeal-help"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/faq"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200
  force = true

# Dynamic SEO proxy for ALL parking company pages
# This wildcard pattern matches all common formats of parking company URLs
[[redirects]]
  from = "/*-parking"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/*-car-park"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/*-car-parks"
  to = "/.netlify/functions/parking-seo"
  status = 200

# Individual company paths that don't follow the patterns above
[[redirects]]
  from = "/ukpc"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/nsl"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/nsgl"
  to = "/.netlify/functions/parking-seo"
  status = 200
  
[[redirects]]
  from = "/ocs"
  to = "/.netlify/functions/parking-seo"
  status = 200
  
[[redirects]]
  from = "/pess"
  to = "/.netlify/functions/parking-seo"
  status = 200

# Known council patterns - STRICT matching only
[[redirects]]
  from = "/*-council"
  to = "/.netlify/functions/council-seo"
  status = 200
  conditions = {Path = [
    "/*-council",
    "!local-authorities",
    "!councils",
    "!council-appeal-hub",
    "!council-list"
  ]}

[[redirects]]
  from = "/*-city-council"
  to = "/.netlify/functions/council-seo"
  status = 200
  conditions = {Path = [
    "/*-city-council",
    "!local-authorities",
    "!councils",
    "!council-appeal-hub",
    "!council-list"
  ]}

[[redirects]]
  from = "/city-of-*"
  to = "/.netlify/functions/council-seo"
  status = 200

# Explicitly listed single-word councils ONLY
[[redirects]]
  from = "/barnsley"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/birmingham"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/bradford"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/coventry"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/leicester"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/leeds"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/liverpool"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/manchester"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/nottingham"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/plymouth"
  to = "/.netlify/functions/council-seo"
  status = 200

# Handle all unknown paths with 404 - MUST BE LAST
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Ensure sitemap.xml and robots.txt are properly served
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# Enable Netlify Functions
[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"
