# Dynamic SEO proxy for ALL parking company pages
# This wildcard pattern matches all common formats of parking company URLs
[[redirects]]
  from = "/*-parking"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/*-car-park"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/*-car-parks"
  to = "/.netlify/functions/parking-seo"
  status = 200

# Individual company paths that don't follow the patterns above
[[redirects]]
  from = "/ukpc"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/nsl"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/nsgl"
  to = "/.netlify/functions/parking-seo"
  status = 200
  
[[redirects]]
  from = "/ocs"
  to = "/.netlify/functions/parking-seo"
  status = 200
  
[[redirects]]
  from = "/pess"
  to = "/.netlify/functions/parking-seo"
  status = 200

# Special exception for council appeal hub page to prevent it being caught by council patterns
[[redirects]]
  from = "/council-appeal-hub"
  to = "/index.html"
  status = 200

# Special exception for the new local authorities page
[[redirects]]
  from = "/local-authorities"
  to = "/index.html"
  status = 200

# Special exception for the councils list page
[[redirects]]
  from = "/councils"
  to = "/index.html"
  status = 200

# Pattern match for known UK councils 
# This must be BEFORE the fallback SPA redirect to prioritize capturing council routes
[[redirects]]
  from = "/*-council"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/*-city-council"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/city-of-*"
  to = "/.netlify/functions/council-seo"
  status = 200

# Individual named council redirects for single-word councils or those that don't follow the patterns above
[[redirects]]
  from = "/barnsley"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/birmingham"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/bradford"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/coventry"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/leicester"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/leeds"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/liverpool"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/manchester"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/nottingham"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/plymouth"
  to = "/.netlify/functions/council-seo"
  status = 200

# Council pages redirects - must come before the catch-all
[[redirects]]
  from = "/:councilSlug"
  to = "/.netlify/functions/council-seo"
  status = 200
  force = false
  conditions = {Path = "/:councilSlug"}

# SPA catch-all route
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure sitemap.xml and robots.txt are properly served
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# Enable Netlify Functions
[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"
