# Dynamic SEO proxy for ALL parking company pages
# This wildcard pattern matches all common formats of parking company URLs
[[redirects]]
  from = "/*-parking"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/*-car-park"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/*-car-parks"
  to = "/.netlify/functions/parking-seo"
  status = 200

# Individual company paths that don't follow the patterns above
[[redirects]]
  from = "/ukpc"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/nsl"
  to = "/.netlify/functions/parking-seo"
  status = 200

[[redirects]]
  from = "/nsgl"
  to = "/.netlify/functions/parking-seo"
  status = 200
  
[[redirects]]
  from = "/ocs"
  to = "/.netlify/functions/parking-seo"
  status = 200
  
[[redirects]]
  from = "/pess"
  to = "/.netlify/functions/parking-seo"
  status = 200

# List of valid React app routes
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/local-authorities"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/councils"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/appeal-help"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/faq"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200
  force = true

# Pattern match for known UK councils - AFTER the React routes
[[redirects]]
  from = "/*-council"
  to = "/.netlify/functions/council-seo"
  status = 200
  conditions = {Path = ["/*-council", "!local-authorities", "!councils", "!council-appeal-hub"]}

[[redirects]]
  from = "/*-city-council"
  to = "/.netlify/functions/council-seo"
  status = 200
  conditions = {Path = ["/*-city-council", "!local-authorities", "!councils", "!council-appeal-hub"]}

[[redirects]]
  from = "/city-of-*"
  to = "/.netlify/functions/council-seo"
  status = 200

# Individual named council redirects for single-word councils
[[redirects]]
  from = "/barnsley"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/birmingham"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/bradford"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/coventry"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/leicester"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/leeds"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/liverpool"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/manchester"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/nottingham"
  to = "/.netlify/functions/council-seo"
  status = 200

[[redirects]]
  from = "/plymouth"
  to = "/.netlify/functions/council-seo"
  status = 200

# Handle unknown paths with 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = true
  conditions = {Path = [
    "!/*-parking",
    "!/*-car-park",
    "!/*-car-parks",
    "!/ukpc",
    "!/nsl",
    "!/nsgl",
    "!/ocs",
    "!/pess",
    "!/",
    "!/local-authorities",
    "!/councils",
    "!/appeal-help",
    "!/faq",
    "!/blog",
    "!/blog/*",
    "!/*-council",
    "!/*-city-council",
    "!/city-of-*",
    "!/barnsley",
    "!/birmingham",
    "!/bradford",
    "!/coventry",
    "!/leicester",
    "!/leeds",
    "!/liverpool",
    "!/manchester",
    "!/nottingham",
    "!/plymouth"
  ]}

# Ensure sitemap.xml and robots.txt are properly served
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# Enable Netlify Functions
[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"
