import React from 'react';
import { Link } from "react-router-dom";
import TrackingButton from "@/components/ui/TrackingButton";
import Image from '@/components/ui/Image';

const AppealSection = () => {
  return (
    <div className="py-24 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          <div className="relative">
            <div className="absolute -inset-4 bg-gradient-to-r from-accent/20 to-secondary/20 rounded-xl blur-xl"></div>
            <div className="relative">
              <Image 
                src="/lovable-uploads/20205d8ab3571-d3cc-4f1a-ac1b-f2ef9753fe50.webp" 
                alt="Appeal letter example generated by Resolvo"
                className="rounded-lg shadow-2xl w-full h-auto object-contain"
                style={{ maxHeight: "600px" }}
                width={540}
                height={720}
                loading="eager"
                fetchPriority="high"
              />
              <p className="text-center mt-4 text-gray-600 text-sm">Written by Resolvo</p>
            </div>
          </div>
          <div>
            <h2 className="text-3xl font-extrabold text-primary">
              Don't let a parking ticket ruin your day
            </h2>
            <p className="mt-4 text-lg text-gray-600">
              Resolvo is trained on the latest parking regulations such as the Traffic Management Act to help you write an appeal in minutes.
            </p>
            <div className="mt-8">
              <TrackingButton
                href="https://chatgpt.com/g/g-C3KOiAkMB-resolvo"
                eventName="appeal_click"
                eventCategory="engagement"
                eventLabel="home_appeal_section"
                className="inline-flex items-center px-6 py-3 border border-transparent text-xl font-medium rounded-lg text-white bg-primary hover:bg-primary/90 transition-all duration-300"
              >
                Appeal now
              </TrackingButton>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AppealSection;